### ISSUE TITLE
bug: Update to Blender 4.2

### ISSUE THREAD

**Issue by thehyenaman** [polygoniq/engon#1]
# Bug Report

Engon 1.2

Error when installing, "bl_name" not defined.

**Comment by Griperis** [comment]
Hi @thehyenaman, thanks for the report. We are making last finishing touches and we should have all our addons compatible with Blender 4.2 in the next days.

**Comment by OneDayCreations** [comment]
Thank you =) much appreciated.

**Comment by Griperis** [comment]
Yesterday we published new release, you can download it from Github or visit https://extensions.polygoniq.com and it will guide you how to set it up as a remote repository.
